config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources 'users' do
    resources 'posts' 
  end
  

  resources 'tags' do
  end

  resources :sessions, :only => [:new, :create, :destroy]

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :about, :only => [:index]
  resources :admin, :only => [:index]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :content
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :content

  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags, allow_destroy: true
  has_many :comments
  belongs_to :user

  default_scope {order('created_at DESC')}

  before_save :get_tags


  def get_tags
    self.tags = self.tags.collect do |tag|
      Tag.find_or_create_by(name: tag.name)
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates_presence_of :name

  has_and_belongs_to_many :posts
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  validates_presence_of :username
  before_save :encrypt_password
  has_many :posts


  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(username, password)
    user = User.where(username: username).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  helper_method :current_user

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @user = current_user
    @post = @user.posts.find(params[:id])
  end

  def new
    if !current_user.admin
      redirect_to root_path
      flash[:alert] = "You don't have permission to do that"
    end
    @post = Post.new
     1.times { @post.tags.build}
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "You did it!! Post posted!"
      redirect_to user_post_path(current_user, @post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_post_path(current_user, @post)
      flash[:notice] = "Success!"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
     params.require(:post).permit(:title, :image, :content, tags_attributes: [:id, :name])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:username], params[:password])
    if @user
      flash[:notice] = "Logged in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "Invalid Username or Password"
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Log out successful"
    redirect_to "/"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Nailed it!!"
    else
      flash[:alert] = "Invalid Username or password"
      render :new
    end
  end


private

  def user_params
    params.require(:user).permit(:password, :username, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="about-container">
  <div class="about-text">
    <h4>Alex Altieri is an aspiring web developer.</h4>
    <h5>She lives in Portland, OR</h5>
  </div>
</div>

app/views/admin/index.html.erb
<%= link_to "Write new post", new_post_path %>

app/views/home/index.html.erb
<div class="home-blog-wrapper clearfix">
  <div class="home-blog clearfix">
    <% if @posts.any? %>
      <h3>Recent Blog Posts</h3>
        <% @posts.take(3).each do |post| %>
          <%= image_tag post.image %>
          <br>
          <h4><%= link_to post.title, post_path(post) %> 
            <br>
            <small>By: <%= post.user_name %> on <%= post.created_at.strftime("%m/%d/%Y at %I:%M%P")  %></small> 
          </h4>
          <% end %>
        <%= link_to "Archive", posts_path %><br>
        <%= link_to "Write New Post", new_post_path %>
    <% else %>
      <h3> Nothing to show. Come back soon!</h3>
    <% end %>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Internet Human</title>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Quicksand:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

  <div id="wrapper">
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
          <li class="sidebar-brand">
            <li>
              <h4><a href="/">Alex Altieri</a></h4>
            </li>
            <li>
              <%= image_tag 'ME.jpg', class: "image-nav"%>
            </li>
            </li>
            <li>
                <a href="/about">About</a>
            </li>
            <li>
                <a href="#">Portfolio</a>
            </li>
            <li>
                <a href="https://www.github.com/AlexAlt">GitHub</a>
            </li>
            <li>
                <a href="https://www.linkedin.com/in/alexaltieri">LinkedIn</a>
            </li>
            <li>
                <a href="users/1/posts">Blog</a>
            </li>
            <% if current_user %>
              <li>
                <a href="/log-out">Log Out</a>
              </li>
            <% else %>
              <li>
                <a href="/log-in">Log In</a>
              </li>
              <li>
                <%= link_to "Sign Up", new_user_path %>
              </li>
            <% end %>
            <% if current_user && current_user.admin %>
              <li>
              <%= link_to "Write New Post", new_user_post_path(current_user) %>
              </li>
            <% end %>
      </ul>
  </div>

    <div id="page-content-wrapper">
      <div class="container-fluid">
        <%= yield %> 
      </div>
    </div>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>


<div class="form-group">
  <%= form_for [current_user, @post] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :image %>
    <%= f.text_field :image %>
    <br>
    <%= f.label :content %>
    <%= f.text_area :content %>
    <br>
    Add a tag: 
    <ul class="list-unstyled">
    <%= f.fields_for :tags do |tags_form| %>
       <li> <%= tags_form.label :name %></li>
        <li><%= tags_form.text_field :name %></li>
        <% end %>
    </ul>
    <%= f.submit  %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h3> Edit Your Post </h3>

<%= render "form" %>

app/views/posts/index.html.erb
<% if @posts.any? %>

  <div class="post-index-wrapper">
    <% @posts.each do |post| %>
      <h4><%= link_to post.title, post_path(post) %> 
        <small>By: <%= post.user %> on <%= post.created_at.strftime("%m/%d/%Y at %I:%M%P")  %></small> 
      </h4>
    <% end %>
  </div>
<% else %>
<h3> Nothing yet! </h3>
<% end %>

app/views/posts/new.html.erb
<h2> What do you have to say today?</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="post-container panel panel-default">
  <h2><%= @post.title %></h2>
  <h4><%= @post.user %> <small><%= @post.created_at.strftime("%m/%d/%Y %I:%M%P") %></small></h4>

  <%= @post.content %>
  <hr>
  <% if @post.tags.any? %>
    <div class="pull-right">
      Tagged as:
      <% @post.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag) %>
      <% end %>
    </div>
  <% end%>
  <br>

  <button class="btn"><%= link_to "Edit", edit_user_post_path %></button>
   <button class="btn btn-link"><%= link_to "Delete Post", user_post_path(@post.user, @post), :data => {:confirm => "You sure?",
    :method => 'delete'} %></button>
</div>

app/views/tags/index.html.erb
<h2>Search posts by tag:</h2>
<% @tags.each do |tag| %>
  <%= link_to tag.name, tag_path(tag) %>
<% end %>

app/views/tags/show.html.erb
<h3> Posts tagged as: <%= @tag.name %> </h3>
  <% if @tag.posts.any? %>
    <% @tag.posts.each do |post| %>
      <%= link_to post.title, post_path(post)%>
      <% end%>
  <% else %>
    <p>No posts with this tag.</p>
  <% end%>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

  <%= form_for @user do |f| %>

    <div class="form-group">
      <%= f.label :username, "Username", class: "control-label" %>
        <%= f.text_field :username, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password, "Password", class: "control-label" %>
        <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, "Confirm Password", class: "control-label" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <%= f.submit "Submit", class: "btn btn-default" %>
  <% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>